on:
  push:
    branches: main
jobs:
  build:
    name: Deploy to cpanel
    runs-on: ubuntu-latest
    steps:
      - name: Executing server update
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{secrets.FTP_HOST}}
          user: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          remoteDir: ${{secrets.DIRECTORY}}
